package com.orientechnologies.orient.test.database.auto;

import static org.testng.AssertJUnit.assertEquals;
import static org.testng.AssertJUnit.assertNotNull;
import static org.testng.AssertJUnit.assertNull;

import com.jetbrains.youtrack.db.internal.core.db.YTDatabaseSession;
import com.jetbrains.youtrack.db.internal.core.db.YTDatabaseSessionInternal;
import com.jetbrains.youtrack.db.internal.core.db.document.YTDatabaseDocumentTx;
import com.jetbrains.youtrack.db.internal.core.db.record.YTIdentifiable;
import com.jetbrains.youtrack.db.internal.core.id.YTRID;
import com.jetbrains.youtrack.db.internal.core.id.YTRecordId;
import com.jetbrains.youtrack.db.internal.core.index.OCompositeKey;
import com.jetbrains.youtrack.db.internal.core.index.OIndex;
import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTClass;
import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTProperty;
import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTSchema;
import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTType;
import com.jetbrains.youtrack.db.internal.core.record.Record;
import com.jetbrains.youtrack.db.internal.core.record.impl.EntityImpl;
import com.jetbrains.youtrack.db.internal.core.sql.executor.YTResultSet;
import java.util.Date;
import java.util.Set;
import java.util.stream.Stream;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * @since 3/3/2015
 */
public class DefaultValuesTrivialTest {

  private static final int DOCUMENT_COUNT = 50;

  private YTDatabaseSessionInternal database;

  @BeforeMethod
  public void before() {
    //noinspection deprecation
    database = new YTDatabaseDocumentTx("memory:" + DefaultValuesTrivialTest.class.getSimpleName());
    //noinspection deprecation
    database.create();
  }

  @AfterMethod
  public void after() {
    //noinspection deprecation
    database.drop();
  }

  @Test
  public void test() {

    // create example schema
    YTSchema schema = database.getMetadata().getSchema();
    YTClass classPerson = schema.createClass("Person");

    classPerson.createProperty(database, "name", YTType.STRING);
    classPerson.createProperty(database, "join_date", YTType.DATETIME)
        .setDefaultValue(database, "sysdate()");
    classPerson.createProperty(database, "active", YTType.BOOLEAN)
        .setDefaultValue(database, "true");

    Date dtStart = getDatabaseSysdate(database);

    EntityImpl[] docs = new EntityImpl[DOCUMENT_COUNT];
    for (int i = 0; i < DOCUMENT_COUNT; ++i) {
      database.begin();
      EntityImpl doc = new EntityImpl("Person");
      doc.field("name", "autoGeneratedName #" + i);
      doc.save();
      database.commit();

      docs[i] = doc;
    }

    Date dtAfter = getDatabaseSysdate(database);
    for (int i = 0; i < DOCUMENT_COUNT; ++i) {
      final EntityImpl doc = docs[i];

      try {
        //
        Date dt = doc.field("join_date", YTType.DATETIME);

        boolean isInRange = (!dt.before(dtStart)) && (!dt.after(dtAfter));
        Assert.assertTrue(isInRange);

        //
        boolean active = doc.field("active", YTType.BOOLEAN);
        Assert.assertTrue(active);
      } catch (Exception ex) {
        ex.printStackTrace();
        Assert.fail();
      }
    }
  }

  private static Date getDatabaseSysdate(YTDatabaseSession database) {
    try (YTResultSet dates = database.query("SELECT sysdate() as sysdate")) {
      return dates.next().getProperty("sysdate");
    }
  }

  @Test
  public void testDefaultValueConversion() {
    YTSchema schema = database.getMetadata().getSchema();
    YTClass classPerson = schema.createClass("Person");
    classPerson.createProperty(database, "users", YTType.LINKSET)
        .setDefaultValue(database, "[#5:1]");

    EntityImpl doc = new EntityImpl("Person");

    database.begin();
    Record record = database.save(doc);
    database.commit();

    EntityImpl doc1 = database.load(record.getIdentity());
    Set<YTIdentifiable> rids = doc1.field("users");
    assertEquals(rids.size(), 1);
    assertEquals(rids.iterator().next(), new YTRecordId(5, 1));
  }

  @Test
  public void testPrepopulation() {
    // create example schema
    YTSchema schema = database.getMetadata().getSchema();
    YTClass classA = schema.createClass("ClassA");

    classA.createProperty(database, "name", YTType.STRING)
        .setDefaultValue(database, "default name");
    classA.createProperty(database, "date", YTType.DATETIME).setDefaultValue(database, "sysdate()");
    classA.createProperty(database, "active", YTType.BOOLEAN).setDefaultValue(database, "true");

    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      assertNotNull(doc.field("date"));
      assertEquals((Boolean) true, doc.field("active"));
    }

    {
      EntityImpl doc = new EntityImpl();
      assertNull(doc.field("name"));
      assertNull(doc.field("date"));
      assertNull(doc.field("active"));
      doc.setClassName(classA.getName());
      assertEquals("default name", doc.field("name"));
      assertNotNull(doc.field("date"));
      assertEquals((Boolean) true, doc.field("active"));
    }

    {
      EntityImpl doc = new EntityImpl();
      assertNull(doc.field("name"));
      assertNull(doc.field("date"));
      assertNull(doc.field("active"));
      doc.setClassNameIfExists(classA.getName());
      assertEquals("default name", doc.field("name"));
      assertNotNull(doc.field("date"));
      assertEquals((Boolean) true, doc.field("active"));
    }
  }

  @Test
  public void testPrepopulationIndex() {
    // create example schema
    YTSchema schema = database.getMetadata().getSchema();
    YTClass classA = schema.createClass("ClassA");

    YTProperty prop = classA.createProperty(database, "name", YTType.STRING);
    prop.setDefaultValue(database, "default name");
    OIndex index = prop.createIndex(database, YTClass.INDEX_TYPE.NOTUNIQUE);

    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      database.begin();
      database.save(doc);
      database.commit();
      try (Stream<YTRID> stream = index.getInternal().getRids(database, "default name")) {
        assertEquals(1, stream.count());
      }
    }
  }

  @Test
  public void testPrepopulationIndexTx() {

    // create example schema
    YTSchema schema = database.getMetadata().getSchema();
    YTClass classA = schema.createClass("ClassA");

    YTProperty prop = classA.createProperty(database, "name", YTType.STRING);
    prop.setDefaultValue(database, "default name");
    OIndex index = prop.createIndex(database, YTClass.INDEX_TYPE.NOTUNIQUE);

    {
      database.begin();
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));

      database.begin();
      database.save(doc);
      database.commit();

      try (Stream<YTRID> stream = index.getInternal().getRids(database, "default name")) {
        assertEquals(1, stream.count());
      }
      database.commit();
      try (Stream<YTRID> stream = index.getInternal().getRids(database, "default name")) {
        assertEquals(1, stream.count());
      }
    }
  }

  @Test
  public void testPrepopulationMultivalueIndex() {

    // create example schema
    YTSchema schema = database.getMetadata().getSchema();
    YTClass classA = schema.createClass("ClassA");

    YTProperty prop = classA.createProperty(database, "name", YTType.STRING);
    prop.setDefaultValue(database, "default name");
    YTProperty prop2 = classA.createProperty(database, "value", YTType.STRING);
    OIndex index = classA.createIndex(database, "multi", YTClass.INDEX_TYPE.NOTUNIQUE, "value",
        "name");

    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      doc.field("value", "1");

      database.begin();
      database.save(doc);
      database.commit();

      try (Stream<YTRID> stream = index.getInternal().getRids(database, new OCompositeKey("1"))) {
        assertEquals(1, stream.count());
      }
    }
    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      doc.field("value", "2");

      database.begin();
      database.save(doc);
      database.commit();

      try (Stream<YTRID> stream = index.getInternal().getRids(database, new OCompositeKey("2"))) {
        assertEquals(1, stream.count());
      }
    }
    try (Stream<YTRID> stream = index.getInternal().getRids(database, new OCompositeKey("3"))) {
      assertEquals(0, stream.count());
    }
  }
}
