package com.orientechnologies.lucene.test;

import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTClass;
import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTSchema;
import com.jetbrains.youtrack.db.internal.core.metadata.schema.YTType;
import com.jetbrains.youtrack.db.internal.core.record.impl.EntityImpl;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 *
 */
public class LuceneSortTest extends BaseLuceneTest {

  private static final String DESCRIPTION =
      "verylong verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylongverylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylongverylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylongverylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong";

  @Before
  public void setUp() throws Exception {
    YTSchema schema = db.getMetadata().getSchema();

    YTClass cls = schema.createClass("Person");
    cls.createProperty(db, "name", YTType.STRING);
    cls.createProperty(db, "surname", YTType.STRING);
    cls.createProperty(db, "description", YTType.STRING);
  }

  @Test
  public void shouldIndexVeryLongDescriptionWithWildCardConfig() throws Exception {

    db.begin();
    db.save(new EntityImpl("Person").field("description", DESCRIPTION));
    db.commit();

    db.command(
            "create index Person.description on Person(description) FULLTEXT ENGINE LUCENE METADATA"
                + " { \"*_index_sorted\" : false }")
        .close();

    long count =
        db.query("SELECT FROM Person WHERE SEARCH_CLASS(\"verylong\")  = true").stream().count();

    Assert.assertEquals(1, count);
  }

  @Test
  public void shouldIndexVeryLongDescriptionWithSingleField() throws Exception {

    db.begin();
    db.save(new EntityImpl("Person").field("description", DESCRIPTION));
    db.commit();

    db.command(
            "create index Person.description on Person(description) FULLTEXT ENGINE LUCENE METADATA"
                + " { \"description_index_sorted\" : false }")
        .close();

    long count =
        db.query("SELECT FROM Person WHERE SEARCH_CLASS(\"verylong\") = true ").stream().count();

    Assert.assertEquals(1, count);
  }
}
