package com.jetbrains.youtrack.db.auto;

import static org.testng.AssertJUnit.assertEquals;
import static org.testng.AssertJUnit.assertNotNull;
import static org.testng.AssertJUnit.assertNull;

import com.jetbrains.youtrack.db.api.DatabaseSession;
import com.jetbrains.youtrack.db.api.query.ResultSet;
import com.jetbrains.youtrack.db.api.record.Identifiable;
import com.jetbrains.youtrack.db.api.record.RID;
import com.jetbrains.youtrack.db.api.record.Record;
import com.jetbrains.youtrack.db.api.schema.Property;
import com.jetbrains.youtrack.db.api.schema.PropertyType;
import com.jetbrains.youtrack.db.api.schema.Schema;
import com.jetbrains.youtrack.db.api.schema.SchemaClass;
import com.jetbrains.youtrack.db.internal.core.db.DatabaseDocumentTx;
import com.jetbrains.youtrack.db.internal.core.db.DatabaseSessionInternal;
import com.jetbrains.youtrack.db.internal.core.id.RecordId;
import com.jetbrains.youtrack.db.internal.core.index.CompositeKey;
import com.jetbrains.youtrack.db.internal.core.index.Index;
import com.jetbrains.youtrack.db.internal.core.record.impl.EntityImpl;
import java.util.Date;
import java.util.Set;
import java.util.stream.Stream;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * @since 3/3/2015
 */
public class DefaultValuesTrivialTest {

  private static final int DOCUMENT_COUNT = 50;

  private DatabaseSessionInternal database;

  @BeforeMethod
  public void before() {
    //noinspection deprecation
    database = new DatabaseDocumentTx("memory:" + DefaultValuesTrivialTest.class.getSimpleName());
    //noinspection deprecation
    database.create();
  }

  @AfterMethod
  public void after() {
    //noinspection deprecation
    database.drop();
  }

  @Test
  public void test() {

    // create example schema
    Schema schema = database.getMetadata().getSchema();
    SchemaClass classPerson = schema.createClass("Person");

    classPerson.createProperty(database, "name", PropertyType.STRING);
    classPerson.createProperty(database, "join_date", PropertyType.DATETIME)
        .setDefaultValue(database, "sysdate()");
    classPerson.createProperty(database, "active", PropertyType.BOOLEAN)
        .setDefaultValue(database, "true");

    Date dtStart = getDatabaseSysdate(database);

    EntityImpl[] docs = new EntityImpl[DOCUMENT_COUNT];
    for (int i = 0; i < DOCUMENT_COUNT; ++i) {
      database.begin();
      EntityImpl doc = new EntityImpl("Person");
      doc.field("name", "autoGeneratedName #" + i);
      doc.save();
      database.commit();

      docs[i] = doc;
    }

    Date dtAfter = getDatabaseSysdate(database);
    for (int i = 0; i < DOCUMENT_COUNT; ++i) {
      final EntityImpl doc = docs[i];

      try {
        //
        Date dt = doc.field("join_date", PropertyType.DATETIME);

        boolean isInRange = (!dt.before(dtStart)) && (!dt.after(dtAfter));
        Assert.assertTrue(isInRange);

        //
        boolean active = doc.field("active", PropertyType.BOOLEAN);
        Assert.assertTrue(active);
      } catch (Exception ex) {
        ex.printStackTrace();
        Assert.fail();
      }
    }
  }

  private static Date getDatabaseSysdate(DatabaseSession database) {
    try (ResultSet dates = database.query("SELECT sysdate() as sysdate")) {
      return dates.next().getProperty("sysdate");
    }
  }

  @Test
  public void testDefaultValueConversion() {
    Schema schema = database.getMetadata().getSchema();
    SchemaClass classPerson = schema.createClass("Person");
    classPerson.createProperty(database, "users", PropertyType.LINKSET)
        .setDefaultValue(database, "[#5:1]");

    EntityImpl doc = new EntityImpl("Person");

    database.begin();
    Record record = database.save(doc);
    database.commit();

    EntityImpl doc1 = database.load(record.getIdentity());
    Set<Identifiable> rids = doc1.field("users");
    assertEquals(rids.size(), 1);
    assertEquals(rids.iterator().next(), new RecordId(5, 1));
  }

  @Test
  public void testPrepopulation() {
    // create example schema
    Schema schema = database.getMetadata().getSchema();
    SchemaClass classA = schema.createClass("ClassA");

    classA.createProperty(database, "name", PropertyType.STRING)
        .setDefaultValue(database, "default name");
    classA.createProperty(database, "date", PropertyType.DATETIME)
        .setDefaultValue(database, "sysdate()");
    classA.createProperty(database, "active", PropertyType.BOOLEAN)
        .setDefaultValue(database, "true");

    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      assertNotNull(doc.field("date"));
      assertEquals((Boolean) true, doc.field("active"));
    }

    {
      EntityImpl doc = new EntityImpl();
      assertNull(doc.field("name"));
      assertNull(doc.field("date"));
      assertNull(doc.field("active"));
      doc.setClassName(classA.getName());
      assertEquals("default name", doc.field("name"));
      assertNotNull(doc.field("date"));
      assertEquals((Boolean) true, doc.field("active"));
    }

    {
      EntityImpl doc = new EntityImpl();
      assertNull(doc.field("name"));
      assertNull(doc.field("date"));
      assertNull(doc.field("active"));
      doc.setClassNameIfExists(classA.getName());
      assertEquals("default name", doc.field("name"));
      assertNotNull(doc.field("date"));
      assertEquals((Boolean) true, doc.field("active"));
    }
  }

  @Test
  public void testPrepopulationIndex() {
    // create example schema
    Schema schema = database.getMetadata().getSchema();
    SchemaClass classA = schema.createClass("ClassA");

    Property prop = classA.createProperty(database, "name", PropertyType.STRING);
    prop.setDefaultValue(database, "default name");
    prop.createIndex(database, SchemaClass.INDEX_TYPE.NOTUNIQUE);

    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      database.begin();
      database.save(doc);
      database.commit();
      try (Stream<RID> stream = database.getIndex("ClassA.name").getInternal()
          .getRids(database, "default name")) {
        assertEquals(1, stream.count());
      }
    }
  }

  @Test
  public void testPrepopulationIndexTx() {

    // create example schema
    Schema schema = database.getMetadata().getSchema();
    SchemaClass classA = schema.createClass("ClassA");

    Property prop = classA.createProperty(database, "name", PropertyType.STRING);
    prop.setDefaultValue(database, "default name");
    prop.createIndex(database, SchemaClass.INDEX_TYPE.NOTUNIQUE);

    {
      database.begin();
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));

      database.begin();
      database.save(doc);
      database.commit();

      var index = database.getIndex("ClassA.name");
      try (Stream<RID> stream = index.getInternal()
          .getRids(database, "default name")) {
        assertEquals(1, stream.count());
      }
      database.commit();

      index = database.getIndex("ClassA.name");
      try (Stream<RID> stream = index.getInternal().getRids(database, "default name")) {
        assertEquals(1, stream.count());
      }
    }
  }

  @Test
  public void testPrepopulationMultivalueIndex() {

    // create example schema
    Schema schema = database.getMetadata().getSchema();
    SchemaClass classA = schema.createClass("ClassA");

    Property prop = classA.createProperty(database, "name", PropertyType.STRING);
    prop.setDefaultValue(database, "default name");
    classA.createProperty(database, "value", PropertyType.STRING);
    classA.createIndex(database, "multi", SchemaClass.INDEX_TYPE.NOTUNIQUE, "value",
        "name");
    Index index = database.getIndex("multi");

    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      doc.field("value", "1");

      database.begin();
      database.save(doc);
      database.commit();

      try (Stream<RID> stream = index.getInternal().getRids(database, new CompositeKey("1"))) {
        assertEquals(1, stream.count());
      }
    }
    {
      EntityImpl doc = new EntityImpl(classA);
      assertEquals("default name", doc.field("name"));
      doc.field("value", "2");

      database.begin();
      database.save(doc);
      database.commit();

      try (Stream<RID> stream = index.getInternal().getRids(database, new CompositeKey("2"))) {
        assertEquals(1, stream.count());
      }
    }
    try (Stream<RID> stream = index.getInternal().getRids(database, new CompositeKey("3"))) {
      assertEquals(0, stream.count());
    }
  }
}
