/* Generated By:JJTree: Do not edit this line. OFromClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import com.jetbrains.youtrack.db.internal.core.db.YTDatabaseSessionInternal;
import com.jetbrains.youtrack.db.internal.core.sql.executor.YTResult;
import com.jetbrains.youtrack.db.internal.core.sql.executor.YTResultInternal;
import java.util.Map;
import java.util.Objects;

public class OFromClause extends SimpleNode {

  protected OFromItem item;

  public OFromClause(int id) {
    super(id);
  }

  public OFromClause(OrientSql p, int id) {
    super(p, id);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (item != null) {
      item.toString(params, builder);
    }
  }

  public void toGenericStatement(StringBuilder builder) {
    if (item != null) {
      item.toGenericStatement(builder);
    }
  }

  public OFromItem getItem() {
    return item;
  }

  public void setItem(OFromItem item) {
    this.item = item;
  }

  public OFromClause copy() {
    OFromClause result = new OFromClause(-1);
    result.item = item.copy();
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    OFromClause that = (OFromClause) o;

    return Objects.equals(item, that.item);
  }

  @Override
  public int hashCode() {
    return item != null ? item.hashCode() : 0;
  }

  public YTResult serialize(YTDatabaseSessionInternal db) {
    YTResultInternal result = new YTResultInternal(db);
    result.setProperty("item", item.serialize(db));
    return result;
  }

  public void deserialize(YTResult fromResult) {
    item = new OFromItem(-1);
    item.deserialize(fromResult.getProperty("item"));
  }

  public boolean isCacheable(YTDatabaseSessionInternal session) {
    return item.isCacheable(session);
  }

  public boolean refersToParent() {
    return item.refersToParent();
  }
}
/* JavaCC - OriginalChecksum=051839d20dabfa4cce26ebcbe0d03a86 (do not edit this line) */
