/* Generated By:JJTree: Do not edit this line. SQLDeleteEdgeToStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

public class SQLDeleteEdgeToStatement extends SQLDeleteEdgeStatement {

  public SQLDeleteEdgeToStatement(int id) {
    super(id);
  }

  public SQLDeleteEdgeToStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public SQLDeleteEdgeStatement copy() {
    return super.copy();
  }
}
/* JavaCC - OriginalChecksum=8b71c6e3bc7262af9a8e0e0ea3a1964c (do not edit this line) */
