/* Generated By:JJTree: Do not edit this line. SQLDeleteEdgeVToStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

public class SQLDeleteEdgeVToStatement extends SQLDeleteEdgeStatement {

  public SQLDeleteEdgeVToStatement(int id) {
    super(id);
  }

  public SQLDeleteEdgeVToStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public SQLDeleteEdgeStatement copy() {
    return super.copy();
  }
}
/* JavaCC - OriginalChecksum=c5435be513de4871657bae94ae2a126b (do not edit this line) */
