/* Generated By:JJTree: Do not edit this line. SQLFindReferencesStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import com.jetbrains.youtrack.db.api.query.ResultSet;
import com.jetbrains.youtrack.db.internal.core.command.BasicCommandContext;
import com.jetbrains.youtrack.db.internal.core.command.CommandContext;
import com.jetbrains.youtrack.db.internal.core.db.DatabaseSessionInternal;
import com.jetbrains.youtrack.db.internal.core.sql.executor.FindReferencesExecutionPlanner;
import com.jetbrains.youtrack.db.internal.core.sql.executor.InternalExecutionPlan;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

public class SQLFindReferencesStatement extends SQLStatement {

  protected SQLRid rid;
  protected SQLStatement subQuery;

  // class or cluster
  protected List<SimpleNode> targets;

  public SQLFindReferencesStatement(int id) {
    super(id);
  }

  public SQLFindReferencesStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean isIdempotent() {
    return true;
  }

  public void addTarget(SimpleNode node) {
    this.targets.add(node);
  }

  @Override
  public ResultSet execute(
      DatabaseSessionInternal db, Object[] args, CommandContext parentCtx,
      boolean usePlanCache) {
    var ctx = new BasicCommandContext();
    if (parentCtx != null) {
      ctx.setParentWithoutOverridingChild(parentCtx);
    }
    ctx.setDatabase(db);
    Map<Object, Object> params = new HashMap<>();
    if (args != null) {
      for (var i = 0; i < args.length; i++) {
        params.put(i, args[i]);
      }
    }
    ctx.setInputParameters(params);
    InternalExecutionPlan executionPlan;
    if (usePlanCache) {
      executionPlan = createExecutionPlan(ctx, false);
    } else {
      executionPlan = createExecutionPlanNoCache(ctx, false);
    }

    return new LocalResultSet(executionPlan);
  }

  @Override
  public ResultSet execute(
      DatabaseSessionInternal db, Map<Object, Object> params, CommandContext parentCtx,
      boolean usePlanCache) {
    var ctx = new BasicCommandContext();
    if (parentCtx != null) {
      ctx.setParentWithoutOverridingChild(parentCtx);
    }
    ctx.setDatabase(db);
    ctx.setInputParameters(params);
    InternalExecutionPlan executionPlan;
    if (usePlanCache) {
      executionPlan = createExecutionPlan(ctx, false);
    } else {
      executionPlan = createExecutionPlanNoCache(ctx, false);
    }

    return new LocalResultSet(executionPlan);
  }

  @Override
  public InternalExecutionPlan createExecutionPlan(CommandContext ctx, boolean enableProfiling) {
    return new FindReferencesExecutionPlanner(this).createExecutionPlan(ctx, enableProfiling);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("FIND REFERENCES ");
    if (rid != null) {
      rid.toString(params, builder);
    } else {
      builder.append(" ( ");
      subQuery.toString(params, builder);
      builder.append(" )");
    }
    if (targets != null) {
      builder.append(" [");
      var first = true;
      for (var node : targets) {
        if (!first) {
          builder.append(",");
        }
        node.toString(params, builder);
        first = false;
      }
      builder.append("]");
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("FIND REFERENCES ");
    if (rid != null) {
      rid.toGenericStatement(builder);
    } else {
      builder.append(" ( ");
      subQuery.toGenericStatement(builder);
      builder.append(" )");
    }
    if (targets != null) {
      builder.append(" [");
      var first = true;
      for (var node : targets) {
        if (!first) {
          builder.append(",");
        }
        node.toGenericStatement(builder);
        first = false;
      }
      builder.append("]");
    }
  }

  @Override
  public SQLFindReferencesStatement copy() {
    var result = new SQLFindReferencesStatement(-1);
    result.rid = rid == null ? null : rid.copy();
    result.subQuery = subQuery == null ? null : subQuery.copy();
    result.targets =
        targets == null ? null : targets.stream().map(x -> x.copy()).collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLFindReferencesStatement) o;

    if (!Objects.equals(rid, that.rid)) {
      return false;
    }
    if (!Objects.equals(subQuery, that.subQuery)) {
      return false;
    }
    return Objects.equals(targets, that.targets);
  }

  @Override
  public int hashCode() {
    var result = rid != null ? rid.hashCode() : 0;
    result = 31 * result + (subQuery != null ? subQuery.hashCode() : 0);
    result = 31 * result + (targets != null ? targets.hashCode() : 0);
    return result;
  }

  public SQLRid getRid() {
    return rid;
  }

  public SQLStatement getSubQuery() {
    return subQuery;
  }

  public List<SimpleNode> getTargets() {
    return targets;
  }
}
/* JavaCC - OriginalChecksum=be781e05acef94aa5edd7438b4ead6d5 (do not edit this line) */
