/* Generated By:JJTree: Do not edit this line. SQLHaSyncClusterStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import com.jetbrains.youtrack.db.api.exception.CommandExecutionException;
import com.jetbrains.youtrack.db.internal.core.command.CommandContext;
import com.jetbrains.youtrack.db.internal.core.sql.executor.resultset.ExecutionStream;
import java.util.Map;

public class SQLHaSyncClusterStatement extends SQLSimpleExecStatement {

  public SQLIdentifier clusterName;
  public boolean modeFull = true;
  public boolean modeMerge = false;

  public SQLHaSyncClusterStatement(int id) {
    super(id);
  }

  public SQLHaSyncClusterStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public ExecutionStream executeSimple(CommandContext ctx) {
    throw new CommandExecutionException(ctx.getDatabaseSession(),
        "Cannot execute HA SYNC CLUSTER, not supported anymore");
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("HA SYNC CLUSTER ");
    clusterName.toString(params, builder);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("HA SYNC CLUSTER ");
    clusterName.toGenericStatement(builder);
  }
}
/* JavaCC - OriginalChecksum=fbf0df8004d889ebc80f39be85008720 (do not edit this line) */
