/* Generated By:JJTree: Do not edit this line. SQLLikeOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import com.jetbrains.youtrack.db.internal.common.collection.OMultiValue;
import com.jetbrains.youtrack.db.internal.core.query.OQueryHelper;
import com.jetbrains.youtrack.db.internal.core.sql.executor.metadata.OIndexFinder.Operation;
import java.util.Map;

public class SQLLikeOperator extends SimpleNode implements SQLBinaryCompareOperator {

  public SQLLikeOperator(int id) {
    super(id);
  }

  public SQLLikeOperator(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean execute(Object iLeft, Object iRight) {
    if (OMultiValue.isMultiValue(iLeft) || OMultiValue.isMultiValue(iRight)) {
      return false;
    }

    if (iLeft == null || iRight == null) {
      return false;
    }
    return OQueryHelper.like(iLeft.toString(), iRight.toString());
  }

  @Override
  public String toString() {
    return "LIKE";
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("LIKE");
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("LIKE");
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Override
  public SQLLikeOperator copy() {
    return this;
  }

  @Override
  public Operation getOperation() {
    return Operation.FuzzyEq;
  }

  @Override
  public boolean equals(Object obj) {
    return obj != null && obj.getClass().equals(this.getClass());
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
/* JavaCC - OriginalChecksum=16d302abf0f85b404e57b964606952ca (do not edit this line) */
