/* Generated By:JJTree: Do not edit this line. SQLStatementSemicolon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import java.util.Map;

public class SQLStatementSemicolon extends SimpleNode {

  public SQLStatementSemicolon(int id) {
    super(id);
  }

  public SQLStatementSemicolon(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    throw new UnsupportedOperationException();
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    throw new UnsupportedOperationException();
  }
}
/* JavaCC - OriginalChecksum=dd666171278492fc7540b6aed7c08733 (do not edit this line) */
