/* Generated By:JJTree: Do not edit this line. SQLTruncateClassStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import com.jetbrains.youtrack.db.api.exception.CommandExecutionException;
import com.jetbrains.youtrack.db.api.query.Result;
import com.jetbrains.youtrack.db.internal.core.command.CommandContext;
import com.jetbrains.youtrack.db.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrack.db.internal.core.sql.executor.resultset.ExecutionStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public class SQLTruncateClassStatement extends DDLStatement {

  protected SQLIdentifier className;
  protected boolean polymorphic = false;
  protected boolean unsafe = false;

  public SQLTruncateClassStatement(int id) {
    super(id);
  }

  public SQLTruncateClassStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public ExecutionStream executeDDL(CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var schema = session.getMetadata().getSchemaInternal();
    var clazz = schema.getClassInternal(className.getStringValue());
    if (clazz == null) {
      throw new CommandExecutionException(session, "Schema Class not found: " + className);
    }

    final var recs = clazz.count(session, polymorphic);
    if (recs > 0 && !unsafe) {
      if (clazz.isSubClassOf(session, "V")) {
        throw new CommandExecutionException(session,
            "'TRUNCATE CLASS' command cannot be used on not empty vertex classes. Apply the"
                + " 'UNSAFE' keyword to force it (at your own risk)");
      } else if (clazz.isSubClassOf(session, "E")) {
        throw new CommandExecutionException(session,
            "'TRUNCATE CLASS' command cannot be used on not empty edge classes. Apply the 'UNSAFE'"
                + " keyword to force it (at your own risk)");
      }
    }

    List<Result> rs = new ArrayList<>();
    var subclasses = clazz.getAllSubclasses(session);
    if (polymorphic && !unsafe) { // for multiple inheritance
      for (var subclass : subclasses) {
        var subclassRecs = clazz.count(session);
        if (subclassRecs > 0) {
          if (subclass.isSubClassOf(session, "V")) {
            throw new CommandExecutionException(session,
                "'TRUNCATE CLASS' command cannot be used on not empty vertex classes ("
                    + subclass.getName(session)
                    + "). Apply the 'UNSAFE' keyword to force it (at your own risk)");
          } else if (subclass.isSubClassOf(session, "E")) {
            throw new CommandExecutionException(session,
                "'TRUNCATE CLASS' command cannot be used on not empty edge classes ("
                    + subclass.getName(session)
                    + "). Apply the 'UNSAFE' keyword to force it (at your own risk)");
          }
        }
      }
    }

    var count = session.truncateClass(clazz.getName(session), false);
    var result = new ResultInternal(session);
    result.setProperty("operation", "truncate class");
    result.setProperty("className", className.getStringValue());
    result.setProperty("count", count);
    rs.add(result);
    if (polymorphic) {
      for (var subclass : subclasses) {
        count = session.truncateClass(subclass.getName(session), false);
        result = new ResultInternal(session);
        result.setProperty("operation", "truncate class");
        result.setProperty("className", className.getStringValue());
        result.setProperty("count", count);
        rs.add(result);
      }
    }

    return ExecutionStream.resultIterator(rs.iterator());
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("TRUNCATE CLASS ");
    className.toString(params, builder);
    if (polymorphic) {
      builder.append(" POLYMORPHIC");
    }
    if (unsafe) {
      builder.append(" UNSAFE");
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("TRUNCATE CLASS ");
    className.toGenericStatement(builder);
    if (polymorphic) {
      builder.append(" POLYMORPHIC");
    }
    if (unsafe) {
      builder.append(" UNSAFE");
    }
  }

  @Override
  public SQLTruncateClassStatement copy() {
    var result = new SQLTruncateClassStatement(-1);
    result.className = className == null ? null : className.copy();
    result.polymorphic = polymorphic;
    result.unsafe = unsafe;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLTruncateClassStatement) o;

    if (polymorphic != that.polymorphic) {
      return false;
    }
    if (unsafe != that.unsafe) {
      return false;
    }
    return Objects.equals(className, that.className);
  }

  @Override
  public int hashCode() {
    var result = className != null ? className.hashCode() : 0;
    result = 31 * result + (polymorphic ? 1 : 0);
    result = 31 * result + (unsafe ? 1 : 0);
    return result;
  }
}
/* JavaCC - OriginalChecksum=301f993f6ba2893cb30c8f189674b974 (do not edit this line) */
