/* Generated By:JJTree: Do not edit this line. SQLUpdateRemoveItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrack.db.internal.core.sql.parser;

import com.jetbrains.youtrack.db.api.query.Result;
import com.jetbrains.youtrack.db.internal.common.collection.MultiValue;
import com.jetbrains.youtrack.db.internal.core.command.CommandContext;
import com.jetbrains.youtrack.db.internal.core.sql.executor.ResultInternal;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

public class SQLUpdateRemoveItem extends SimpleNode {

  protected SQLExpression left;
  protected SQLExpression right;

  public SQLUpdateRemoveItem(int id) {
    super(id);
  }

  public SQLUpdateRemoveItem(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    left.toString(params, builder);
    if (right != null) {
      builder.append(" = ");
      right.toString(params, builder);
    }
  }

  public void toGenericStatement(StringBuilder builder) {
    left.toGenericStatement(builder);
    if (right != null) {
      builder.append(" = ");
      right.toGenericStatement(builder);
    }
  }

  public SQLUpdateRemoveItem copy() {
    var result = new SQLUpdateRemoveItem(-1);
    result.left = left == null ? null : left.copy();
    result.right = right == null ? null : right.copy();
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLUpdateRemoveItem) o;

    if (!Objects.equals(left, that.left)) {
      return false;
    }
    return Objects.equals(right, that.right);
  }

  @Override
  public int hashCode() {
    var result = left != null ? left.hashCode() : 0;
    result = 31 * result + (right != null ? right.hashCode() : 0);
    return result;
  }

  public void applyUpdate(ResultInternal result, CommandContext ctx) {
    if (right != null) {
      var leftVal = left.execute(result, ctx);
      var rightVal = right.execute(result, ctx);
      if (rightVal instanceof Result && ((Result) rightVal).isEntity()) {
        rightVal = ((Result) rightVal).castToEntity();
      }
      if (rightVal instanceof Collection<?>
          && ((Collection<?>) rightVal)
          .stream().allMatch(x -> x instanceof Result && ((Result) x).isEntity())) {
        rightVal =
            ((Collection<?>) rightVal)
                .stream()
                .map(x -> ((Result) x).castToEntity())
                .collect(Collectors.toList());
      }
      if (MultiValue.isMultiValue(leftVal)) {
        MultiValue.remove(leftVal, rightVal, false);
        if (MultiValue.isMultiValue(rightVal)) {
          var iter = MultiValue.getMultiValueIterator(rightVal);
          while (iter.hasNext()) {
            var item = iter.next();
            if (item instanceof Result && ((Result) item).getIdentity() != null) {
              MultiValue.remove(leftVal, ((Result) item).getIdentity(), false);
            } else {
              MultiValue.remove(leftVal, item, false);
            }
          }
        }
      }
    } else {
      left.applyRemove(result, ctx);
    }
  }
}
/* JavaCC - OriginalChecksum=72e240d3dc1196fdea69e8fdc2bd69ca (do not edit this line) */
